### ISSUE TITLE
codex CLI fails in CI environments (GitHub Actions) due to Ink raw mode error, even with --quiet, CODEX_QUIET_MODE=1, and --no-terminal

### ISSUE THREAD

**Issue by charlie87041** [openai/codex#1080]
### What version of Codex is running?

0.1.2505172129

### Which model were you using?

default. just trying demos in CI pipeline

### What platform is your computer?

github actions

### What steps can reproduce the bug?

Running the Codex CLI in GitHub Actions fails with an Ink-related stdin error, even when using recommended non-interactive flags and environment variables.

Environment

Runner: ubuntu-latest (GitHub Actions)

Node: 22.15.0

Codex CLI installed globally: npm install -g @openai/codex

Prompt: any (e.g. "Update CHANGELOG" or "Look for vulnerabilities...")

What I tried;
```
jobs:
   ...
    env:
       CODEX_QUIET_MODE: 1
```
```
codex -a auto-edit --quiet "Update CHANGELOG for next release"
codex --no-terminal "Look for vulnerabilities and create a security review report"
```
And also `export CODEX_QUIET_MODE=1` and `codex --quiet --no-terminal ...`  in the step 

### What is the expected behavior?

A valid response of the codex app

### What do you see instead?

ERROR Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported

### Additional information

This is the relevant action code

```
  name: Codex review integration
  
  on:
    push:
      branches: [ "master" ]
  
  concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true
  
  jobs:
    codex-review:
      runs-on: ubuntu-latest
      env:
        OPENAI_API_KEY: ${{ secrets.CODEX_API_KEY }}
        CODEX_QUIET_MODE: 1 #deshabilita el modo consola para git action
      permissions:
        contents: read
        pull-requests: write
  
      steps:
        - name: Use Node.js 22
          uses: actions/setup-node@v4
          with:
            node-version: '22'
  
  
        - name: Install Codex CLI
          run: npm install -g @openai/codex
  
        - name: Check Codex CLI version
          run: codex --version
  
        # Ejemplo de paso: actualizar changelog automáticamente
        - name: Auto-update CHANGELOG with Codex
          run: |
            export CODEX_QUIET_MODE=1
            codex --no-terminal  -a auto-edit "Update CHANGELOG for next release"
  
  
        # Otro paso: revisión de seguridad (puedes duplicar con diferentes prompts)
        - name: Security review with Codex
          run: |
            codex --quiet "Look for vulnerabilities and create a security review report"
  
        # Otro paso: sugerencia de PRs útiles
        - name: Suggest high-impact PRs
          run: |
            codex --quiet "Carefully review this repo, and propose 3 high impact well-scoped PRs"
```
