### ISSUE TITLE
GH action Codex: codex action is not published?

### ISSUE THREAD

**Issue by da1z** [openai/codex#1317]
```
      - name: Run Codex
        uses: openai/codex-action@latest
        with:
          openai_api_key: ${{ secrets.CODEX_OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codex_home: ./.github/codex/home

```

Unable to resolve action `openai/codex-action@latest`, repository or version not found

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/29830eae-0fd6-4857-b696-c4032806d32d" />
