### ISSUE TITLE
Runing codex in github action

### ISSUE THREAD

**Issue by JuHyung-Son** [openai/codex#412]
### What is the issue?

I followed this in action
```
- name: Update changelog via Codex
  run: |
    npm install -g @openai/codex
    export OPENAI_API_KEY="${{ secrets.OPENAI_KEY }}"
    codex -a auto-edit --quiet "update CHANGELOG for next release"
```

but It failed with 

```
{"role":"user","content":[{"type":"input_text","text":"Plz review code 1) Explain what this PR does\\n2) Code review and suggestions for improvement\\n3) Detect bugs and potential bugs. \\nUpdate in review.md in korean language"}],"type":"message"}
Please pass patch text through stdin
```

Also, I test in local linux,

```bash
root@43d1ec8385b1:/codex# cat READMD.md | codex -q -a auto-edit "summary"
{"role":"user","content":[{"type":"input_text","text":"summary"}],"type":"message"}
Patch must start with *** Begin Patch\n
```

so I added *** Begin Patch\n on REDME.md and I got,

```bash
root@2deea6cb9463:~/codex# cat README.md | codex --full-auto -q "here "
{"role":"user","content":[{"type":"input_text","text":"here "}],"type":"message"}
Invalid patch text
```

**Comment by eriklueth** [comment]
Same here, the github action fails with "Please pass patch text through stdin"

```
    - name: Generate fixes with Codex CLI (CI mode)
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Build instruction from issue
        INSTR="Fix the following issue: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}. ${{ github.event.issue.body }}"
        # Run in non-interactive auto-edit mode: prompt first, then approval mode flag
        codex -a auto-edit --quiet "$INSTR"
```
